<?php
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountryCodesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country_codes', function (Blueprint $table) {
            $table->id();
            $table->string('code');
            $table->string('country');
            $table->enum('status',['Active','Inactive'])->default('Active');
            $table->timestamps();
        });

        DB::table('country_codes')->insert([
            [ 'code' =>  'AF', 'country' =>  'Afghanistan', 'status' =>  'Active'],
            [ 'code' =>  'AX', 'country' =>  'Aland Islands', 'status' =>  'Active'],
            [ 'code' =>  'AL', 'country' =>  'Albania', 'status' =>  'Active'],
            [ 'code' =>  'DZ', 'country' =>  'Algeria', 'status' =>  'Active'],
            [ 'code' =>  'AS', 'country' =>  'American Samoa', 'status' =>  'Active'],
            [ 'code' =>  'AD', 'country' =>  'Andorra', 'status' =>  'Active'],
            [ 'code' =>  'AO', 'country' =>  'Angola', 'status' =>  'Active'],
            [ 'code' =>  'AI', 'country' =>  'Anguilla', 'status' =>  'Active'],
            [ 'code' =>  'AQ', 'country' =>  'Antarctica', 'status' =>  'Active'],
            [ 'code' =>  'AG', 'country' =>  'Antigua and Barbuda', 'status' =>  'Active'],
            [ 'code' =>  'AR', 'country' =>  'Argentina', 'status' =>  'Active'],
            [ 'code' =>  'AM', 'country' =>  'Armenia', 'status' =>  'Active'],
            [ 'code' =>  'AW', 'country' =>  'Aruba', 'status' =>  'Active'],
            [ 'code' =>  'AU', 'country' =>  'Australia', 'status' =>  'Active'],
            [ 'code' =>  'AT', 'country' =>  'Austria', 'status' =>  'Active'],
            [ 'code' =>  'AZ', 'country' =>  'Azerbaijan', 'status' =>  'Active'],
            [ 'code' =>  'BS', 'country' =>  'Bahamas the', 'status' =>  'Active'],
            [ 'code' =>  'BH', 'country' =>  'Bahrain', 'status' =>  'Active'],
            [ 'code' =>  'BD', 'country' =>  'Bangladesh', 'status' =>  'Active'],
            [ 'code' =>  'BB', 'country' =>  'Barbados', 'status' =>  'Active'],
            [ 'code' =>  'BY', 'country' =>  'Belarus', 'status' =>  'Active'],
            [ 'code' =>  'BE', 'country' =>  'Belgium', 'status' =>  'Active'],
            [ 'code' =>  'BZ', 'country' =>  'Belize', 'status' =>  'Active'],
            [ 'code' =>  'BJ', 'country' =>  'Benin', 'status' =>  'Active'],
            [ 'code' =>  'BM', 'country' =>  'Bermuda', 'status' =>  'Active'],
            [ 'code' =>  'BT', 'country' =>  'Bhutan', 'status' =>  'Active'],
            [ 'code' =>  'BO', 'country' =>  'Bolivia', 'status' =>  'Active'],
            [ 'code' =>  'BA', 'country' =>  'Bosnia and Herzegovina', 'status' =>  'Active'],
            [ 'code' =>  'BW', 'country' =>  'Botswana', 'status' =>  'Active'],
            [ 'code' =>  'BV', 'country' =>  'Bouvet Island', 'status' =>  'Active'],
            [ 'code' =>  'BR', 'country' =>  'Brazil', 'status' =>  'Active'],
            [ 'code' =>  'IO', 'country' =>  'British Indian Ocean Territory', 'status' =>  'Active'],
            [ 'code' =>  'VG', 'country' =>  'British Virgin Islands', 'status' =>  'Active'],
            [ 'code' =>  'BN', 'country' =>  'Brunei Darussalam', 'status' =>  'Active'],
            [ 'code' =>  'BG', 'country' =>  'Bulgaria', 'status' =>  'Active'],
            [ 'code' =>  'BF', 'country' =>  'Burkina Faso', 'status' =>  'Active'],
            [ 'code' =>  'BI', 'country' =>  'Burundi', 'status' =>  'Active'],
            [ 'code' =>  'KH', 'country' =>  'Cambodia', 'status' =>  'Active'],
            [ 'code' =>  'CM', 'country' =>  'Cameroon', 'status' =>  'Active'],
            [ 'code' =>  'CA', 'country' =>  'Canada', 'status' =>  'Active'],
            [ 'code' =>  'CV', 'country' =>  'Cape Verde', 'status' =>  'Active'],
            [ 'code' =>  'KY', 'country' =>  'Cayman Islands', 'status' =>  'Active'],
            [ 'code' =>  'CF', 'country' =>  'Central African Republic', 'status' =>  'Active'],
            [ 'code' =>  'TD', 'country' =>  'Chad', 'status' =>  'Active'],
            [ 'code' =>  'CL', 'country' =>  'Chile', 'status' =>  'Active'],
            [ 'code' =>  'CN', 'country' =>  'China', 'status' =>  'Active'],
            [ 'code' =>  'CX', 'country' =>  'Christmas Island', 'status' =>  'Active'],
            [ 'code' =>  'CC', 'country' =>  'Cocos Islands', 'status' =>   'Active'],
            [ 'code' =>  'CO', 'country' =>  'Colombia', 'status' =>  'Active'],
            [ 'code' =>  'KM', 'country' =>  'Comoros the', 'status' =>  'Active'],
            [ 'code' =>  'CD', 'country' =>  'Congo', 'status' =>  'Active'],
            [ 'code' =>  'CG', 'country' =>  'Congo the', 'status' =>  'Active'],
            [ 'code' =>  'CK', 'country' =>  'Cook Islands', 'status' =>  'Active'],
            [ 'code' =>  'CR', 'country' =>  'Costa Rica', 'status' =>  'Active'],
            [ 'code' =>  'CI', 'country' =>  'Cote d\Ivoire', 'status' =>  'Active'],
            [ 'code' =>  'HR', 'country' =>  'Croatia', 'status' =>  'Active'],
            [ 'code' =>  'CU', 'country' =>  'Cuba', 'status' =>  'Active'],
            [ 'code' =>  'CY', 'country' =>  'Cyprus', 'status' =>  'Active'],
            [ 'code' =>  'CZ', 'country' =>  'Czech Republic', 'status' =>  'Active'],
            [ 'code' =>  'DK', 'country' =>  'Denmark', 'status' =>  'Active'],
            [ 'code' =>  'DJ', 'country' =>  'Djibouti', 'status' =>  'Active'],
            [ 'code' =>  'DM', 'country' =>  'Dominica', 'status' =>  'Active'],
            [ 'code' =>  'DO', 'country' =>  'Dominican Republic', 'status' =>  'Active'],
            [ 'code' =>  'EC', 'country' =>  'Ecuador', 'status' =>  'Active'],
            [ 'code' =>  'EG', 'country' =>  'Egypt', 'status' =>  'Active'],
            [ 'code' =>  'SV', 'country' =>  'El Salvador', 'status' =>  'Active'],
            [ 'code' =>  'GQ', 'country' =>  'Equatorial Guinea', 'status' =>  'Active'],
            [ 'code' =>  'ER', 'country' =>  'Eritrea', 'status' =>  'Active'],
            [ 'code' =>  'EE', 'country' =>  'Estonia', 'status' =>  'Active'],
            [ 'code' =>  'ET', 'country' =>  'Ethiopia', 'status' =>  'Active'],
            [ 'code' =>  'FO', 'country' =>  'Faroe Islands', 'status' =>  'Active'],
            [ 'code' =>  'FK', 'country' =>  'Falkland Islands', 'status' =>  'Active'],
            [ 'code' =>  'FJ', 'country' =>  'Fiji the Fiji Islands', 'status' =>  'Active'],
            [ 'code' =>  'FI', 'country' =>  'Finland', 'status' =>  'Active'],
            [ 'code' =>  'FR', 'country' =>  'France - French Republic', 'Active'],
            [ 'code' =>  'GF', 'country' =>  'French Guiana', 'status' =>  'Active'],
            [ 'code' =>  'PF', 'country' =>  'French Polynesia', 'status' =>  'Active'],
            [ 'code' =>  'TF', 'country' =>  'French Southern Territories', 'status' =>  'Active'],
            [ 'code' =>  'GA', 'country' =>  'Gabon', 'status' =>  'Active'],
            [ 'code' =>  'GM', 'country' =>  'Gambia the', 'status' =>  'Active'],
            [ 'code' =>  'GE', 'country' =>  'Georgia', 'status' =>  'Active'],
            [ 'code' =>  'DE', 'country' =>  'Germany', 'status' =>  'Active'],
            [ 'code' =>  'GH', 'country' =>  'Ghana', 'status' =>  'Active'],
            [ 'code' =>  'GI', 'country' =>  'Gibraltar', 'status' =>  'Active'],
            [ 'code' =>  'GR', 'country' =>  'Greece', 'status' =>  'Active'],
            [ 'code' =>  'GL', 'country' =>  'Greenland', 'status' =>  'Active'],
            [ 'code' =>  'GD', 'country' =>  'Grenada', 'status' =>  'Active'],
            [ 'code' =>  'GP', 'country' =>  'Guadeloupe', 'status' =>  'Active'],
            [ 'code' =>  'GU', 'country' =>  'Guam', 'status' =>  'Active'],
            [ 'code' =>  'GT', 'country' =>  'Guatemala', 'status' =>  'Active'],
            [ 'code' =>  'GG', 'country' =>  'Guernsey', 'status' =>  'Active'],
            [ 'code' =>  'GN', 'country' =>  'Guinea', 'status' =>  'Active'],
            [ 'code' =>  'GW', 'country' =>  'Guinea-Bissau', 'status' =>  'Active'],
            [ 'code' =>  'GY', 'country' =>  'Guyana', 'status' =>  'Active'],
            [ 'code' =>  'HT', 'country' =>  'Haiti', 'status' =>  'Active'],
            [ 'code' =>  'HM', 'country' =>  'Heard Island and McDonald Islands', 'status' =>  'Active'],
            [ 'code' =>  'VA', 'country' =>  'Holy See - Vatican City State', 'status' =>   'Active'],
            [ 'code' =>  'HN', 'country' =>  'Honduras', 'status' =>  'Active'],
            [ 'code' =>  'HK', 'country' =>  'Hong Kong', 'status' =>  'Active'],
            [ 'code' =>  'HU', 'country' =>  'Hungary', 'status' =>  'Active'],
            [ 'code' =>  'IS', 'country' =>  'Iceland', 'status' =>  'Active'],
            [ 'code' =>  'IN', 'country' =>  'India', 'status' =>  'Active'],
            [ 'code' =>  'ID', 'country' =>  'Indonesia', 'status' =>  'Active'],
            [ 'code' =>  'IR', 'country' =>  'Iran', 'status' =>  'Active'],
            [ 'code' =>  'IQ', 'country' =>  'Iraq', 'status' =>  'Active'],
            [ 'code' =>  'IE', 'country' =>  'Ireland', 'status' =>  'Active'],
            [ 'code' =>  'IM', 'country' =>  'Isle of Man', 'status' =>  'Active'],
            [ 'code' =>  'IL', 'country' =>  'Israel', 'status' =>  'Active'],
            [ 'code' =>  'IT', 'country' =>  'Italy', 'status' =>  'Active'],
            [ 'code' =>  'JM', 'country' =>  'Jamaica', 'status' =>  'Active'],
            [ 'code' =>  'JP', 'country' =>  'Japan', 'status' =>  'Active'],
            [ 'code' =>  'JE', 'country' =>  'Jersey', 'status' =>  'Active'],
            [ 'code' =>  'JO', 'country' =>  'Jordan', 'status' =>  'Active'],
            [ 'code' =>  'KZ', 'country' =>  'Kazakhstan', 'status' =>  'Active'],
            [ 'code' =>  'KE', 'country' =>  'Kenya', 'status' =>  'Active'],
            [ 'code' =>  'KI', 'country' =>  'Kiribati', 'status' =>  'Active'],
            [ 'code' =>  'KP', 'country' =>  'Korea', 'status' =>  'Active'],
            [ 'code' =>  'KR', 'country' =>  'Korea', 'status' =>  'Active'],
            [ 'code' =>  'KW', 'country' =>  'Kuwait', 'status' =>  'Active'],
            [ 'code' =>  'KG', 'country' =>  'Kyrgyz Republic', 'status' =>  'Active'],
            [ 'code' =>  'LA', 'country' =>  'Lao', 'status' =>  'Active'],
            [ 'code' =>  'LV', 'country' =>  'Latvia', 'status' =>  'Active'],
            [ 'code' =>  'LB', 'country' =>  'Lebanon', 'status' =>  'Active'],
            [ 'code' =>  'LS', 'country' =>  'Lesotho', 'status' =>  'Active'],
            [ 'code' =>  'LR', 'country' =>  'Liberia', 'status' =>  'Active'],
            [ 'code' =>  'LY', 'country' =>  'Libyan Arab Jamahiriya', 'status' =>  'Active'],
            [ 'code' =>  'LI', 'country' =>  'Liechtenstein', 'status' =>  'Active'],
            [ 'code' =>  'LT', 'country' =>  'Lithuania', 'status' =>  'Active'],
            [ 'code' =>  'LU', 'country' =>  'Luxembourg', 'status' =>  'Active'],
            [ 'code' =>  'MO', 'country' =>  'Macao', 'status' =>  'Active'],
            [ 'code' =>  'MK', 'country' =>  'Macedonia', 'status' =>  'Active'],
            [ 'code' =>  'MG', 'country' =>  'Madagascar', 'status' =>  'Active'],
            [ 'code' =>  'MW', 'country' =>  'Malawi', 'status' =>  'Active'],
            [ 'code' =>  'MY', 'country' =>  'Malaysia', 'status' =>  'Active'],
            [ 'code' =>  'MV', 'country' =>  'Maldives', 'status' =>  'Active'],
            [ 'code' =>  'ML', 'country' =>  'Mali', 'status' =>  'Active'],
            [ 'code' =>  'MT', 'country' =>  'Malta', 'status' =>  'Active'],
            [ 'code' =>  'MH', 'country' =>  'Marshall Islands', 'status' =>  'Active'],
            [ 'code' =>  'MQ', 'country' =>  'Martinique', 'status' =>  'Active'],
            [ 'code' =>  'MR', 'country' =>  'Mauritania', 'status' =>  'Active'],
            [ 'code' =>  'MU', 'country' =>  'Mauritius', 'status' =>  'Active'],
            [ 'code' =>  'YT', 'country' =>  'Mayotte', 'status' =>  'Active'],
            [ 'code' =>  'MX', 'country' =>  'Mexico', 'status' =>  'Active'],
            [ 'code' =>  'FM', 'country' =>  'Micronesia', 'status' =>  'Active'],
            [ 'code' =>  'MD', 'country' =>  'Moldova', 'status' =>  'Active'],
            [ 'code' =>  'MC', 'country' =>  'Monaco', 'status' =>  'Active'],
            [ 'code' =>  'MN', 'country' =>  'Mongolia', 'status' =>  'Active'],
            [ 'code' =>  'ME', 'country' =>  'Montenegro', 'status' =>  'Active'],
            [ 'code' =>  'MS', 'country' =>  'Montserrat', 'status' =>  'Active'],
            [ 'code' =>  'MA', 'country' =>  'Morocco', 'status' =>  'Active'],
            [ 'code' =>  'MZ', 'country' =>  'Mozambique', 'status' =>  'Active'],
            [ 'code' =>  'MM', 'country' =>  'Myanmar', 'status' =>  'Active'],
            [ 'code' =>  'NA', 'country' =>  'Namibia', 'status' =>  'Active'],
            [ 'code' =>  'NR', 'country' =>  'Nauru', 'status' =>  'Active'],
            [ 'code' =>  'NP', 'country' =>  'Nepal', 'status' =>  'Active'],
            [ 'code' =>  'AN', 'country' =>  'Netherlands Antilles', 'status' =>  'Active'],
            [ 'code' =>  'NL', 'country' =>  'Netherlands the', 'status' =>  'Active'],
            [ 'code' =>  'NC', 'country' =>  'New Caledonia', 'status' =>  'Active'],
            [ 'code' =>  'NZ', 'country' =>  'New Zealand', 'status' =>  'Active'],
            [ 'code' =>  'NI', 'country' =>  'Nicaragua', 'status' =>  'Active'],
            [ 'code' =>  'NE', 'country' =>  'Niger', 'status' =>  'Active'],
            [ 'code' =>  'NG', 'country' =>  'Nigeria', 'status' =>  'Active'],
            [ 'code' =>  'NU', 'country' =>  'Niue', 'status' =>  'Active'],
            [ 'code' =>  'NF', 'country' =>  'Norfolk Island', 'status' =>  'Active'],
            [ 'code' =>  'MP', 'country' =>  'Northern Mariana Islands', 'status' =>  'Active'],
            [ 'code' =>  'NO', 'country' =>  'Norway', 'status' =>  'Active'],
            [ 'code' =>  'OM', 'country' =>  'Oman', 'status' =>  'Active'],
            [ 'code' =>  'PK', 'country' =>  'Pakistan', 'status' =>  'Active'],
            [ 'code' =>  'PW', 'country' =>  'Palau', 'status' =>  'Active'],
            [ 'code' =>  'PS', 'country' =>  'Palestinian Territory', 'status' =>  'Active'],
            [ 'code' =>  'PA', 'country' =>  'Panama', 'status' =>  'Active'],
            [ 'code' =>  'PG', 'country' =>  'Papua New Guinea', 'status' =>  'Active'],
            [ 'code' =>  'PY', 'country' =>  'Paraguay', 'status' =>  'Active'],
            [ 'code' =>  'PE', 'country' =>  'Peru', 'status' =>  'Active'],
            [ 'code' =>  'PH', 'country' =>  'Philippines', 'status' =>  'Active'],
            [ 'code' =>  'PN', 'country' =>  'Pitcairn Islands', 'status' =>  'Active'],
            [ 'code' =>  'PL', 'country' =>  'Poland', 'status' =>  'Active'],
            [ 'code' =>  'PT', 'country' =>  'Portugal Portuguese Republic', 'Active'],
            [ 'code' =>  'PR', 'country' =>  'Puerto Rico', 'status' =>  'Active'],
            [ 'code' =>  'QA', 'country' =>  'Qatar', 'status' =>  'Active'],
            [ 'code' =>  'RE', 'country' =>  'Reunion', 'status' =>  'Active'],
            [ 'code' =>  'RO', 'country' =>  'Romania', 'status' =>  'Active'],
            [ 'code' =>  'RU', 'country' =>  'Russian Federation', 'status' =>  'Active'],
            [ 'code' =>  'RW', 'country' =>  'Rwanda', 'status' =>  'Active'],
            [ 'code' =>  'BL', 'country' =>  'Saint Barthelemy', 'status' =>  'Active'],
            [ 'code' =>  'SH', 'country' =>  'Saint Helena', 'status' =>  'Active'],
            [ 'code' =>  'KN', 'country' =>  'Saint Kitts and Nevis', 'status' =>  'Active'],
            [ 'code' =>  'LC', 'country' =>  'Saint Lucia', 'status' =>  'Active'],
            [ 'code' =>  'MF', 'country' =>  'Saint Martin', 'status' =>  'Active'],
            [ 'code' =>  'PM', 'country' =>  'Saint Pierre and Miquelon', 'status' =>  'Active'],
            [ 'code' =>  'VC', 'country' =>  'Saint Vincent and the Grenadines', 'status' =>  'Active'],
            [ 'code' =>  'WS', 'country' =>  'Samoa', 'status' =>  'Active'],
            [ 'code' =>  'SM', 'country' =>  'San Marino', 'status' =>  'Active'],
            [ 'code' =>  'ST', 'country' =>  'Sao Tome and Principe', 'status' =>  'Active'],
            [ 'code' =>  'SA', 'country' =>  'Saudi Arabia', 'status' =>  'Active'],
            [ 'code' =>  'SN', 'country' =>  'Senegal', 'status' =>  'Active'],
            [ 'code' =>  'RS', 'country' =>  'Serbia', 'status' =>  'Active'],
            [ 'code' =>  'SC', 'country' =>  'Seychelles', 'status' =>  'Active'],
            [ 'code' =>  'SL', 'country' =>  'Sierra Leone', 'status' =>  'Active'],
            [ 'code' =>  'SG', 'country' =>  'Singapore', 'status' =>  'Active'],
            [ 'code' =>  'SK', 'country' =>  'Slovakia - Slovak Republic', 'status' =>   'Active'],
            [ 'code' =>  'SI', 'country' =>  'Slovenia', 'status' =>  'Active'],
            [ 'code' =>  'SB', 'country' =>  'Solomon Islands', 'status' =>  'Active'],
            [ 'code' =>  'SO', 'country' =>  'Somalia Somali Republic', 'Active'],
            [ 'code' =>  'ZA', 'country' =>  'South Africa', 'status' =>  'Active'],
            [ 'code' =>  'GS', 'country' =>  'South Georgia and the South Sandwich Islands', 'status' =>  'Active'],
            [ 'code' =>  'ES', 'country' =>  'Spain', 'status' =>  'Active'],
            [ 'code' =>  'LK', 'country' =>  'Sri Lanka', 'status' =>  'Active'],
            [ 'code' =>  'SD', 'country' =>  'Sudan', 'status' =>  'Active'],
            [ 'code' =>  'SR', 'country' =>  'Suriname', 'status' =>  'Active'],
            [ 'code' =>  'SJ', 'country' =>  'Svalbard & Jan Mayen Islands', 'status' =>  'Active'],
            [ 'code' =>  'SZ', 'country' =>  'Swaziland', 'status' =>  'Active'],
            [ 'code' =>  'SE', 'country' =>  'Sweden', 'status' =>  'Active'],
            [ 'code' =>  'CH', 'country' =>  'Switzerland Swiss Confederation', 'Active'],
            [ 'code' =>  'SY', 'country' =>  'Syrian Arab Republic', 'status' =>  'Active'],
            [ 'code' =>  'TW', 'country' =>  'Taiwan', 'status' =>  'Active'],
            [ 'code' =>  'TJ', 'country' =>  'Tajikistan', 'status' =>  'Active'],
            [ 'code' =>  'TZ', 'country' =>  'Tanzania', 'status' =>  'Active'],
            [ 'code' =>  'TH', 'country' =>  'Thailand', 'status' =>  'Active'],
            [ 'code' =>  'TL', 'country' =>  'Timor-Leste', 'status' =>  'Active'],
            [ 'code' =>  'TG', 'country' =>  'Togo', 'status' =>  'Active'],
            [ 'code' =>  'TK', 'country' =>  'Tokelau', 'status' =>  'Active'],
            [ 'code' =>  'TO', 'country' =>  'Tonga', 'status' =>  'Active'],
            [ 'code' =>  'TT', 'country' =>  'Trinidad and Tobago', 'status' =>  'Active'],
            [ 'code' =>  'TN', 'country' =>  'Tunisia', 'status' =>  'Active'],
            [ 'code' =>  'TR', 'country' =>  'Turkey', 'status' =>  'Active'],
            [ 'code' =>  'TM', 'country' =>  'Turkmenistan', 'status' =>  'Active'],
            [ 'code' =>  'TC', 'country' =>  'Turks and Caicos Islands', 'status' =>  'Active'],
            [ 'code' =>  'TV', 'country' =>  'Tuvalu', 'status' =>  'Active'],
            [ 'code' =>  'UG', 'country' =>  'Uganda', 'status' =>  'Active'],
            [ 'code' =>  'UA', 'country' =>  'Ukraine', 'status' =>  'Active'],
            [ 'code' =>  'AE', 'country' =>  'United Arab Emirates', 'status' =>  'Active'],
            [ 'code' =>  'GB', 'country' =>  'United Kingdom', 'status' =>  'Active'],
            [ 'code' =>  'US', 'country' =>  'United States of America', 'status' =>  'Active'],
            [ 'code' =>  'UM', 'country' =>  'United States Minor Outlying Islands', 'status' =>  'Active'],
            [ 'code' =>  'VI', 'country' =>  'United States Virgin Islands', 'status' =>  'Active'],
            [ 'code' =>  'UY', 'country' =>  'Uruguay', 'status' =>  'Active'],
            [ 'code' =>  'UZ', 'country' =>  'Uzbekistan', 'status' =>  'Active'],
            [ 'code' =>  'VU', 'country' =>  'Vanuatu', 'status' =>  'Active'],
            [ 'code' =>  'VE', 'country' =>  'Venezuela', 'status' =>  'Active'],
            [ 'code' =>  'VN', 'country' =>  'Vietnam', 'status' =>  'Active'],
            [ 'code' =>  'WF', 'country' =>  'Wallis and Futuna', 'status' =>  'Active'],
            [ 'code' =>  'EH', 'country' =>  'Western Sahara', 'status' =>  'Active'],
            [ 'code' =>  'YE', 'country' =>  'Yemen', 'status' =>  'Active'],
            [ 'code' =>  'ZM', 'country' =>  'Zambia', 'status' =>  'Active'],
            [ 'code' =>  'ZW', 'country' =>  'Zimbabwe', 'status' =>  'Active']


        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('attribute_values');
    }
}
