<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateAffiliatePaymentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('affiliate_payments', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('affiliate_id')->unsigned()->nullable();
            $table->foreign('affiliate_id')->on('users')->references('id');
            $table->bigInteger('order_id')->unsigned()->nullable();
            $table->foreign('order_id')->on('orders')->references('id');
            $table->float('amount',8,2)->nullable();
            $table->date('paid_date')->nullable();
            $table->enum('status',['Pending','Approved','Paid'])->default('Pending');

            $table->timestamps();
        });

        DB::table('affiliate_payments')->insert([
            [
                "affiliate_id"=>4,
                "order_id"=>1,
                "amount"=>"3.56",
                "paid_date"=>"2020-10-04",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>5,
                "amount"=>"8.51",
                "paid_date"=>"2022-03-14",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>4,
                "amount"=>"3.86",
                "paid_date"=>"2021-10-21",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>8,
                "amount"=>"3.69",
                "paid_date"=>"2022-02-27",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>8,
                "amount"=>"8.38",
                "paid_date"=>"2020-10-09",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>9,
                "amount"=>"7.60",
                "paid_date"=>"2021-01-27",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>10,
                "amount"=>"3.36",
                "paid_date"=>"2020-11-09",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>9,
                "amount"=>"1.03",
                "paid_date"=>"2020-10-20",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>6,
                "amount"=>"7.81",
                "paid_date"=>"2020-12-27",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>10,
                "amount"=>"5.50",
                "paid_date"=>"2020-10-19",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>10,
                "amount"=>"3.31",
                "paid_date"=>"2021-03-25",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>6,
                "amount"=>"3.77",
                "paid_date"=>"2020-10-29",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>1,
                "amount"=>"5.68",
                "paid_date"=>"2022-07-17",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>9,
                "amount"=>"3.97",
                "paid_date"=>"2021-05-12",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>3,
                "amount"=>"3.84",
                "paid_date"=>"2022-01-25",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>1,
                "amount"=>"4.80",
                "paid_date"=>"2022-02-03",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>2,
                "amount"=>"3.07",
                "paid_date"=>"2022-06-02",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>4,
                "amount"=>"5.29",
                "paid_date"=>"2021-07-28",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>8,
                "amount"=>"8.81",
                "paid_date"=>"2022-05-16",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>1,
                "amount"=>"1.14",
                "paid_date"=>"2022-06-07",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>6,
                "amount"=>"1.53",
                "paid_date"=>"2021-01-02",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>5,
                "amount"=>"2.07",
                "paid_date"=>"2021-07-25",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>5,
                "amount"=>"7.77",
                "paid_date"=>"2021-01-05",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>1,
                "amount"=>"4.56",
                "paid_date"=>"2022-03-23",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>7,
                "amount"=>"5.83",
                "paid_date"=>"2021-12-10",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>1,
                "amount"=>"4.89",
                "paid_date"=>"2021-10-19",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>1,
                "amount"=>"1.98",
                "paid_date"=>"2022-08-18",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>9,
                "amount"=>"6.15",
                "paid_date"=>"2022-06-10",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>9,
                "amount"=>"4.70",
                "paid_date"=>"2022-02-13",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>6,
                "amount"=>"4.90",
                "paid_date"=>"2021-03-05",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>10,
                "amount"=>"4.73",
                "paid_date"=>"2020-11-04",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>4,
                "amount"=>"1.68",
                "paid_date"=>"2022-01-30",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>2,
                "order_id"=>8,
                "amount"=>"4.14",
                "paid_date"=>"2021-07-21",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>10,
                "amount"=>"3.00",
                "paid_date"=>"2022-02-18",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>4,
                "order_id"=>7,
                "amount"=>"7.26",
                "paid_date"=>"2020-10-29",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>3,
                "amount"=>"3.76",
                "paid_date"=>"2022-08-07",
                "status"=>"Pending"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>10,
                "amount"=>"5.31",
                "paid_date"=>"2022-05-06",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>3,
                "order_id"=>3,
                "amount"=>"4.26",
                "paid_date"=>"2022-03-23",
                "status"=>"Paid"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>1,
                "amount"=>"8.04",
                "paid_date"=>"2021-03-13",
                "status"=>"Approved"
            ],
            [
                "affiliate_id"=>1,
                "order_id"=>7,
                "amount"=>"6.01",
                "paid_date"=>"2020-12-21",
                "status"=>"Paid"
            ]

        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('affiliate_payments');
    }
}
